In [9]:
import numpy as np
import pandas
import geopy as gp
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut

geolocator = Nominatim(user_agent="hello")

In [18]:
df = pandas.read_csv('HODP Athlete Project - All Athletes.csv', index_col = 0)
df = df[pandas.notnull(df['Hometown'])]
df = df.reset_index()
df.drop(columns = ['Unnamed: 8'])
df.head()

,Sport,Gender,Name,Yr.,Hometown,High School,"Median Household Income from datausa.io, or ZIP code from https://www.incomebyzipcode.com",Private School,Unnamed: 8
0,Baseball,M,Seamus Buckley,Fy,"Dorchester, Mass.",Beaver Country Day,"71,723",1,"103,092"
1,Baseball,M,Ian Buckner,Fy,"Oak Park, Calif.",Grace Brethren Academy,"129,721",1,NaN
2,Baseball,M,Will Jacobsen,Fy,"San Francisco, Calif.",The Branson School,"110,816",1,NaN
3,Baseball,M,Ben Rounds,Fy,"Milton, Mass.",Roxbury Latin,"126,000",1,NaN
4,Baseball,M,Pryor Thomas,Fy,"Keller, Texas",Liberty Christian School,126013,1,NaN

In [13]:
print(df.iloc[0].Hometown)

Dorchester, Mass.

In [14]:
def do_geocode(address):
    try:
        return geolocator.geocode(address)
    except GeocoderTimedOut:
        return do_geocode(address)

In [15]:
print(do_geocode("New York, New York"))

New York, United States of America

In [23]:
# Cleaner function
def cleaner(old, new):
    lst = [] 
    for i, row in df.iterrows():
        if old in row["Hometown"]:
            lst.append(i)

    print(lst)
    for i in lst:
        df.iloc[i]["Hometown"] = df.iloc[i]["Hometown"].replace(old, new)
        
cleaner("Ill.", "Illinois")
cleaner("Neb.", "Nebraska")
cleaner("Wisc.", "Wisconsin")
cleaner("Fla", "Florida")
cleaner("Coquitlan", "Coquitlam")
cleaner("Pozos de Santa", "Pozos")
cleaner("Cutchouge", "Cutchogue")
cleaner("Edgarton", "Edgartown")

[43, 70, 74, 77, 167, 204, 216, 220, 279, 360, 444, 452, 455, 456, 458, 497, 515, 541, 548, 620, 632, 639, 673, 675, 682, 699, 702, 759, 769, 779, 822, 863, 909, 992, 993, 1003, 1030]
[73]
[121, 568, 714]
[8, 57, 107, 157, 163, 206, 244, 245, 254, 256, 284, 317, 334, 339, 340, 424, 436, 466, 471, 476, 494, 519, 553, 580, 595, 600, 631, 648, 667, 670, 830, 847, 927, 946, 947, 948, 1049]
[474, 598]
[662]
[732]
[967]

In [24]:
print(df.iloc[732].Hometown)

Cutchogue, N.Y.

In [25]:
df = df.iloc[0:len(df.Hometown)]
df

,Sport,Gender,Name,Yr.,Hometown,High School,"Median Household Income from datausa.io, or ZIP code from https://www.incomebyzipcode.com",Private School,Unnamed: 8
0,Baseball,M,Seamus Buckley,Fy,"Dorchester, Mass.",Beaver Country Day,"71,723",1,"103,092"
1,Baseball,M,Ian Buckner,Fy,"Oak Park, Calif.",Grace Brethren Academy,"129,721",1,NaN
2,Baseball,M,Will Jacobsen,Fy,"San Francisco, Calif.",The Branson School,"110,816",1,NaN
3,Baseball,M,Ben Rounds,Fy,"Milton, Mass.",Roxbury Latin,"126,000",1,NaN
4,Baseball,M,Pryor Thomas,Fy,"Keller, Texas",Liberty Christian School,126013,1,NaN
...,...,...,...,...,...,...,...,...,...
1047,Tennis,F,Mihaela Marculescu,First-Year,"Bucharest, Romania",Tudor Vianu,NaN,NaN,NaN
1048,Tennis,F,Lexi Milunovich,Senior,"New Canaan, Conn.",Greenwich Academy,"147,128",NaN,NaN
1049,Tennis,F,Demi Snyder,First-Year,"Ft. Lauderdale, Florida.",Pine Crest School,"52,315",NaN,NaN
1050,Tennis,F,Chelsea Williams,Sophomore,"Brooklyn, N.Y.",Brooklyn Technical,"85,846",NaN,NaN
1051,Tennis,F,Lauryn Wu,First-Year,"McLean, Va.",Thomas Jefferson High School for Science and T...,NaN,NaN,NaN

In [ ]:
def do_geocode(address):
    try:
        return geolocator.geocode(address)
    except GeocoderTimedOut:
        return do_geocode(address)


df['CHometown'] = df.apply(lambda row: print(do_geocode(row["Hometown"]) do_geocode(row["Hometown"]).address, axis=1)

In [29]:
df['CHometown'] = 'dvalue'
locations = []
 # for index, row in df.iterrows():
    # location = do_geocode(row["Hometown"])
   #  print(index)
   #  print(location.address)
   #  locations.append(location.address)
   #  df.loc[index, 'CHometown'] = location.address

c:\users\richa\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

0
Dorchester, Boston, Suffolk County, Massachusetts, 02124, United States

c:\users\richa\appdata\local\programs\python\python37\lib\site-packages\pandas\core\indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
c:\users\richa\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

1
Oak Park, Ventura County, California, 91377, United States
2
San Francisco, San Francisco City and County, California, United States of America
3
Milton, Norfolk County, Massachusetts, United States of America
4
Keller, Tarrant County, Texas, United States
5
Northridge, Los Angeles, Los Angeles County, California, United States of America
6
Cypress, Harris County, Texas, 77433, United States
7
Stamford, Fairfield, Connecticut, United States
8
Plantation, Broward County, Florida, United States
9
Far Hills, Somerset County, New Jersey, United States
10
Medfield, Norfolk County, Massachusetts, 02052, United States of America
11
Duxbury, Plymouth County, Massachusetts, United States of America
12
Wellesley, Norfolk County, Massachusetts, United States of America
13
Darien, Fairfield, Connecticut, 06820, United States
14
Los Angeles, Los Angeles County, California, United States of America
15
Washington, District of Columbia, United States
16
Houston, Harris County, Texas, United States of America
17
Manhattan Beach, Los Angeles County, California, 90266, United States
18
Andover, Essex County, Massachusetts, United States of America
19
Katy, Fort Bend County, Texas, United States
20
Toronto, Golden Horseshoe, Ontario, M6K 1X9, Canada
21
Houston, Harris County, Texas, United States of America
22
Nashville-Davidson, Davidson County, Tennessee, United States of America
23
Fulshear, Fort Bend County, Texas, 77441, United States
24
Douglasville, Douglas County, Georgia, United States of America
25
Del Mar, San Diego County, California, United States
26
Huntington Beach, Orange County, California, United States of America
27
Los Gatos, Santa Clara County, California, United States
28
Stamford, Fairfield, Connecticut, United States
29
Pacific Palisades, Los Angeles, Los Angeles County, California, 90272-3719, United States
30
Alpharetta, Fulton County, Georgia, United States
31
Etobicoke, Toronto, Golden Horseshoe, Ontario, Canada
32
Brooklyn, Kings County, New York, United States of America
33
Brooklyn, Kings County, New York, United States of America
34
Richmond, Richmond City, Virginia, 23298, United States
35
Ottawa, Eastern Ontario, Ontario, K1P 1J1, Canada
36
Randolph, Norfolk County, Massachusetts, United States of America
37
Pacific Palisades, Los Angeles, Los Angeles County, California, 90272-3719, United States
38
Lexington, Middlesex County, Massachusetts, United States
39
Denver, Denver County, Colorado, United States of America
40
Folsom, Sacramento County, California, United States
41
Tarzana, Los Angeles, Los Angeles County, California, 91356, United States
42
O’Fallon, Saint Charles County, Missouri, United States of America
43
Glencoe, Cook County, Illinois, United States
44
Brampton, Peel Region, Golden Horseshoe, Ontario, Canada
45
Columbus, Franklin County, Ohio, United States of America
46
La Jolla, San Diego County, California, 92037, United States
47
Woodstock, Cherokee County, Georgia, 30075:30188, United States
48
Redondo Beach, Los Angeles County, California, United States
49
Havertown, Delaware County, Pennsylvania, 19083, United States
50
Guaynabo, Puerto Rico, 00969, United States of America
51
Winston-Salem, Forsyth County, North Carolina, United States

KeyboardInterrupt:

In [92]:
import csv

with open('Hometowns.csv', 'w', newline='') as myfile:
     wr = csv.writer(myfile, quoting=csv.QUOTE_ALL)
     wr.writerow(locations)